### ISSUE TITLE
Change some columns  names

### ISSUE THREAD

**Issue by JavierArredondo** [alercebroker/db-plugins#1]
In [magnitude_statistics model](https://github.com/alercebroker/db-plugins/blob/master/db_plugins/db/sql/models.py#L149) we have some names out of context. Compare with this [document]( https://docs.google.com/spreadsheets/d/1OH3Dz-s8pWy-cY2FuT59miItHMrpIRm1aOVCRTPwLGA/edit#gid=1052063955). Maybe we need change the schema for different magnitudes e.g: magnitude_type = ["psf", "ap"]. 
So we have 3 pkey = ("oid", "fid", "magnitude_type"). In bulk process we consider this data but each row have psf and ap data.

Possible solution: Add to document magnitude_type or chose psf/ap for model

**Comment by cvalenzu** [comment]
Schema updated to the latest db schema
