### ISSUE TITLE
[question] Is necessary index on meanra and meandec?

### ISSUE THREAD

**Issue by JavierArredondo** [alercebroker/db-plugins#23]
I think those indexes are redundant if exists `loc_2dsphere` index for cone search

https://github.com/alercebroker/db-plugins/blob/b458fe1d97aa95f790f01d640642764e6e5a73d5/db_plugins/db/mongo/models.py#L55-L56

**Comment by pcastelln** [comment]
It is currently slated for elimination in next version with multistream
