### ISSUE TITLE
[question] oid is not considered a field? 

### ISSUE THREAD

**Issue by JavierArredondo** [alercebroker/db-plugins#24]
We don't consider `oid` as a primary field. Is it correct? 

https://github.com/alercebroker/db-plugins/blob/b458fe1d97aa95f790f01d640642764e6e5a73d5/db_plugins/db/mongo/models.py#L61-L88

**Comment by dirodriguezm** [comment]
I don't know. In terms of what a detection is, the `aid` and `tid` are enough. The typical use case is to get the lightcurve of an ALeRCE ID, and to differentiate the source, there's `tid`. I think that in this schema, we want to make the `oid` less important and give full priority to the `aid`.

**Comment by JavierArredondo** [comment]
My complication is that we cannot provide light curve tracking for specific surveys. Maybe we are ignoring some scientific cases for astronomers. What do you think @ale-munozarancibia (in the context of the detection)?

A typical case that occurs to me is that I know an specific `oid` like ZTF20aeelulu, so I could retrieve specifically that light curve.

**Comment by dirodriguezm** [comment]
You could do the spatial query. Eventually what you would know as the `oid` would be the `aid` "AL20something" if we make such naming nomenclature. (AL from ALeRCE, 20 the year, and then the regular aid based on the coordinates)

**Comment by JavierArredondo** [comment]
ok, we can keep oid in the `extra_fields`

**Comment by ale-munozarancibia** [comment]
I think it's ok to have it as an extra field for now, and if our experiments later show that it's critical to have it as a primary one, then can be added later

**Comment by dirodriguezm** [comment]
I'm going to close it for now, but feel free to reopen as needed
