### ISSUE TITLE
Improve performance for probability updates of multistream database

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/db-plugins#46]
The update probability logic is too slow for multistream database (mongodb). We should look for a way to do bulk updates instead of 1 by 1.

The code we have to modify is https://github.com/alercebroker/db-plugins/blob/feat/mongo_helper/db_plugins/db/mongo/helpers/update_probs.py

Pipeline steps using this code:
- https://github.com/alercebroker/transformer_online_classifier_step

**Comment by AlxEnashi** [comment]
More insigth is required but this changes aparently didint impact the performance in a meaningfull way.

**Comment by pgallardor** [comment]
@AlxEnashi Do we have any new info about the performance?
