### ISSUE TITLE
Obtain the performance of find queries in integration tests

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/db-plugins#54]

**Comment by pgallardor** [comment]
_Task title changed: Update queries are based on find queries since we need to search the elements we want to update._

**Comment by pgallardor** [comment]
@pcastelln Performed experiments to get the execution times and memory usage of the **find by probability** queries using different types of indexation.

![Image](https://user-images.githubusercontent.com/20263599/207644354-b12760bd-a035-42c5-8700-63fc0c9a296c.png)



![Image](https://user-images.githubusercontent.com/20263599/207644397-f9d0c82a-0a18-4285-97c7-8087a81231d2.png)
