### ISSUE TITLE
Check viability of new mongo models

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/db-plugins#55]
The new version of DB pluggins, with mongo models may not be retrocompatible with the current data in the database.
If it isn't there will be needed to dessinign a plan to deploy the new version.

**Comment by AlxEnashi** [comment]
Two trials were designed.
The first, db_plugins queries  set, as integratioon test, but ussiing a db with data, the idea is to check every query used in the api and steps loking for erros.
The seccond, deploy a complete local pipeline, populate the mongo db with some data, test if all the steps run correctly.
